//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:07:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class logDto
    {
        [DataMember()]
        public Int32 i_IdLogError { get; set; }

        [DataMember()]
        public Nullable<Int32> i_SystemUserId { get; set; }

        [DataMember()]
        public String v_Error { get; set; }

        [DataMember()]
        public String v_Exception { get; set; }

        [DataMember()]
        public String v_InformacionAdicional { get; set; }

        [DataMember()]
        public String v_NombrePC { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_FechaHoraError { get; set; }

        public logDto()
        {
        }

        public logDto(Int32 i_IdLogError, Nullable<Int32> i_SystemUserId, String v_Error, String v_Exception, String v_InformacionAdicional, String v_NombrePC, Nullable<DateTime> t_FechaHoraError)
        {
			this.i_IdLogError = i_IdLogError;
			this.i_SystemUserId = i_SystemUserId;
			this.v_Error = v_Error;
			this.v_Exception = v_Exception;
			this.v_InformacionAdicional = v_InformacionAdicional;
			this.v_NombrePC = v_NombrePC;
			this.t_FechaHoraError = t_FechaHoraError;
        }
    }
}
