//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:11:15
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class planillaafectacionesgeneralesDto
    {
        [DataMember()]
        public Int32 i_Id { get; set; }

        [DataMember()]
        public String v_Periodo { get; set; }

        [DataMember()]
        public String v_Mes { get; set; }

        [DataMember()]
        public String v_IdConceptoPlanilla { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Leyes_Trab_ONP { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Leyes_Trab_Senati { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Leyes_Trab_SCTR { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Leyes_Emp_Essalud { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Leyes_Emp_SCTR { get; set; }

        [DataMember()]
        public Nullable<Int32> i_AFP_Afecto { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Rent5ta_Afecto { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_InsertaFecha { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_ActualizaFecha { get; set; }

        [DataMember()]
        public planillaconceptosDto planillaconceptos { get; set; }

        public planillaafectacionesgeneralesDto()
        {
        }

        public planillaafectacionesgeneralesDto(Int32 i_Id, String v_Periodo, String v_Mes, String v_IdConceptoPlanilla, Nullable<Int32> i_Leyes_Trab_ONP, Nullable<Int32> i_Leyes_Trab_Senati, Nullable<Int32> i_Leyes_Trab_SCTR, Nullable<Int32> i_Leyes_Emp_Essalud, Nullable<Int32> i_Leyes_Emp_SCTR, Nullable<Int32> i_AFP_Afecto, Nullable<Int32> i_Rent5ta_Afecto, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<DateTime> t_ActualizaFecha, planillaconceptosDto planillaconceptos)
        {
			this.i_Id = i_Id;
			this.v_Periodo = v_Periodo;
			this.v_Mes = v_Mes;
			this.v_IdConceptoPlanilla = v_IdConceptoPlanilla;
			this.i_Leyes_Trab_ONP = i_Leyes_Trab_ONP;
			this.i_Leyes_Trab_Senati = i_Leyes_Trab_Senati;
			this.i_Leyes_Trab_SCTR = i_Leyes_Trab_SCTR;
			this.i_Leyes_Emp_Essalud = i_Leyes_Emp_Essalud;
			this.i_Leyes_Emp_SCTR = i_Leyes_Emp_SCTR;
			this.i_AFP_Afecto = i_AFP_Afecto;
			this.i_Rent5ta_Afecto = i_Rent5ta_Afecto;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.planillaconceptos = planillaconceptos;
        }
    }
}
