//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:11:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class recibohonorariodetalleDto
    {
        [DataMember()]
        public String v_IdReciboHonorarioDetalle { get; set; }

        [DataMember()]
        public String v_IdReciboHonorario { get; set; }

        [DataMember()]
        public String v_NroCuenta { get; set; }

        [DataMember()]
        public String i_CCosto { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_ImporteSoles { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_ImporteDolares { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_InsertaFecha { get; set; }

        [DataMember()]
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_ActualizaFecha { get; set; }

        [DataMember()]
        public recibohonorarioDto recibohonorario { get; set; }

        public recibohonorariodetalleDto()
        {
        }

        public recibohonorariodetalleDto(String v_IdReciboHonorarioDetalle, String v_IdReciboHonorario, String v_NroCuenta, String i_CCosto, Nullable<Decimal> d_ImporteSoles, Nullable<Decimal> d_ImporteDolares, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_ActualizaFecha, recibohonorarioDto recibohonorario)
        {
			this.v_IdReciboHonorarioDetalle = v_IdReciboHonorarioDetalle;
			this.v_IdReciboHonorario = v_IdReciboHonorario;
			this.v_NroCuenta = v_NroCuenta;
			this.i_CCosto = i_CCosto;
			this.d_ImporteSoles = d_ImporteSoles;
			this.d_ImporteDolares = d_ImporteDolares;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.recibohonorario = recibohonorario;
        }
    }
}
