//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/19 - 12:50:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System.Text;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class transportistachoferDto
    {
        [DataMember()]
        public string v_IdChofer { get; set; }

        [DataMember()]
        public string v_IdTransportista { get; set; }

        [DataMember()]
        public string v_NombreCompleto { get; set; }

        [DataMember()]
        public string v_Brevete { get; set; }

        [DataMember()]
        public int? i_Eliminado { get; set; }

        [DataMember()]
        public int? i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public DateTime? t_InsertaFecha { get; set; }

        [DataMember()]
        public int? i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public DateTime? t_ActualizaFecha { get; set; }

        [DataMember()]
        public int? i_IdTipoIdentificacion { get; set; }

        [DataMember()]
        public string v_NroDocIdentificacion { get; set; }

        [DataMember()]
        public List<string> guiaremision_v_IdGuiaRemision { get; set; }

        public transportistachoferDto()
        {
        }

        public transportistachoferDto(string v_IdChofer, string v_IdTransportista, string v_NombreCompleto, string v_Brevete, int? i_Eliminado, int? i_InsertaIdUsuario, DateTime? t_InsertaFecha, int? i_ActualizaIdUsuario, DateTime? t_ActualizaFecha, int? i_IdTipoIdentificacion, string v_NroDocIdentificacion, List<string> guiaremision_v_IdGuiaRemision)
        {
			this.v_IdChofer = v_IdChofer;
			this.v_IdTransportista = v_IdTransportista;
			this.v_NombreCompleto = v_NombreCompleto;
			this.v_Brevete = v_Brevete;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.i_IdTipoIdentificacion = i_IdTipoIdentificacion;
			this.v_NroDocIdentificacion = v_NroDocIdentificacion;
			this.guiaremision_v_IdGuiaRemision = guiaremision_v_IdGuiaRemision;
        }
    }
}