//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:10:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class nbs_ordentrabajodetalleDto
    {
        [DataMember()]
        public String v_IdOrdenTrabajoDetalle { get; set; }

        [DataMember()]
        public String v_IdOrdenTrabajo { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Cantidad { get; set; }

        [DataMember()]
        public String v_IdProductoDetalle { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_Importe { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_Total { get; set; }

        [DataMember()]
        public String v_Glosa { get; set; }

        [DataMember()]
        public Nullable<Int32> i_UsadoEnFUF { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_InsertaFecha { get; set; }

        [DataMember()]
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_ActualizaFecha { get; set; }

        [DataMember()]
        public String v_DescripcionTemporal { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_ImporteRegistral { get; set; }

        [DataMember()]
        public nbs_ordentrabajoDto nbs_ordentrabajo { get; set; }

        [DataMember()]
        public productodetalleDto productodetalle { get; set; }

        public nbs_ordentrabajodetalleDto()
        {
        }

        public nbs_ordentrabajodetalleDto(String v_IdOrdenTrabajoDetalle, String v_IdOrdenTrabajo, Nullable<Int32> i_Cantidad, String v_IdProductoDetalle, Nullable<Decimal> d_Importe, Nullable<Decimal> d_Total, String v_Glosa, Nullable<Int32> i_UsadoEnFUF, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_ActualizaFecha, String v_DescripcionTemporal, Nullable<Decimal> d_ImporteRegistral, nbs_ordentrabajoDto nbs_ordentrabajo, productodetalleDto productodetalle)
        {
			this.v_IdOrdenTrabajoDetalle = v_IdOrdenTrabajoDetalle;
			this.v_IdOrdenTrabajo = v_IdOrdenTrabajo;
			this.i_Cantidad = i_Cantidad;
			this.v_IdProductoDetalle = v_IdProductoDetalle;
			this.d_Importe = d_Importe;
			this.d_Total = d_Total;
			this.v_Glosa = v_Glosa;
			this.i_UsadoEnFUF = i_UsadoEnFUF;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.v_DescripcionTemporal = v_DescripcionTemporal;
			this.d_ImporteRegistral = d_ImporteRegistral;
			this.nbs_ordentrabajo = nbs_ordentrabajo;
			this.productodetalle = productodetalle;
        }
    }
}
