//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:07:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class conceptoscajachicaDto
    {
        [DataMember()]
        public Int32 i_IdConceptosCajaChica { get; set; }

        [DataMember()]
        public String v_NombreConceptoCajaChica { get; set; }

        [DataMember()]
        public String v_NroCuenta { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_Cantidad { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_InsertaFecha { get; set; }

        [DataMember()]
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_ActualizaFecha { get; set; }

        [DataMember()]
        public Nullable<Int32> i_RequiereTipoDocumento { get; set; }

        [DataMember()]
        public Nullable<Int32> i_RequiereNumeroDocumento { get; set; }

        [DataMember()]
        public Nullable<Int32> i_RequiereAnexo { get; set; }

        [DataMember()]
        public List<cajachicadetalleDto> cajachicadetalle { get; set; }

        public conceptoscajachicaDto()
        {
        }

        public conceptoscajachicaDto(Int32 i_IdConceptosCajaChica, String v_NombreConceptoCajaChica, String v_NroCuenta, Nullable<Decimal> d_Cantidad, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_ActualizaFecha, Nullable<Int32> i_RequiereTipoDocumento, Nullable<Int32> i_RequiereNumeroDocumento, Nullable<Int32> i_RequiereAnexo, List<cajachicadetalleDto> cajachicadetalle)
        {
			this.i_IdConceptosCajaChica = i_IdConceptosCajaChica;
			this.v_NombreConceptoCajaChica = v_NombreConceptoCajaChica;
			this.v_NroCuenta = v_NroCuenta;
			this.d_Cantidad = d_Cantidad;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.i_RequiereTipoDocumento = i_RequiereTipoDocumento;
			this.i_RequiereNumeroDocumento = i_RequiereNumeroDocumento;
			this.i_RequiereAnexo = i_RequiereAnexo;
			this.cajachicadetalle = cajachicadetalle;
        }
    }
}
