//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:12:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="loghistorial"/> and <see cref="loghistorialDto"/>.
    /// </summary>
    public static partial class loghistorialAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="loghistorialDto"/> converted from <see cref="loghistorial"/>.</param>
        static partial void OnDTO(this loghistorial entity, loghistorialDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="loghistorial"/> converted from <see cref="loghistorialDto"/>.</param>
        static partial void OnEntity(this loghistorialDto dto, loghistorial entity);

        /// <summary>
        /// Converts this instance of <see cref="loghistorialDto"/> to an instance of <see cref="loghistorial"/>.
        /// </summary>
        /// <param name="dto"><see cref="loghistorialDto"/> to convert.</param>
        public static loghistorial ToEntity(this loghistorialDto dto)
        {
            if (dto == null) return null;

            var entity = new loghistorial();

            entity.i_IdHistorial = dto.i_IdHistorial;
            entity.v_Accion = dto.v_Accion;
            entity.v_NombrePC = dto.v_NombrePC;
            entity.t_FechaHora = dto.t_FechaHora;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="loghistorial"/> to an instance of <see cref="loghistorialDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="loghistorial"/> to convert.</param>
        public static loghistorialDto ToDTO(this loghistorial entity)
        {
            if (entity == null) return null;

            var dto = new loghistorialDto();

            dto.i_IdHistorial = entity.i_IdHistorial;
            dto.v_Accion = entity.v_Accion;
            dto.v_NombrePC = entity.v_NombrePC;
            dto.t_FechaHora = entity.t_FechaHora;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="loghistorialDto"/> to an instance of <see cref="loghistorial"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<loghistorial> ToEntities(this IEnumerable<loghistorialDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="loghistorial"/> to an instance of <see cref="loghistorialDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<loghistorialDto> ToDTOs(this IEnumerable<loghistorial> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
