//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/08/24 - 19:46:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class configuracionbalancesDto
    {
        [DataMember()]
        public Int32 i_IdConfiguracionBalance { get; set; }

        [DataMember()]
        public String v_TipoBalance { get; set; }

        [DataMember()]
        public String v_Codigo { get; set; }

        [DataMember()]
        public String v_Nombre { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_InsertaFecha { get; set; }

        [DataMember()]
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_ActualizaFecha { get; set; }

        [DataMember()]
        public String v_NombreGrupo { get; set; }

        [DataMember()]
        public Nullable<Int32> i_TipoNota { get; set; }

        [DataMember()]
        public String v_Mes { get; set; }

        [DataMember()]
        public String v_Periodo { get; set; }

        public configuracionbalancesDto()
        {
        }

        public configuracionbalancesDto(Int32 i_IdConfiguracionBalance, String v_TipoBalance, String v_Codigo, String v_Nombre, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_ActualizaFecha, String v_NombreGrupo, Nullable<Int32> i_TipoNota, String v_Mes, String v_Periodo)
        {
			this.i_IdConfiguracionBalance = i_IdConfiguracionBalance;
			this.v_TipoBalance = v_TipoBalance;
			this.v_Codigo = v_Codigo;
			this.v_Nombre = v_Nombre;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.v_NombreGrupo = v_NombreGrupo;
			this.i_TipoNota = i_TipoNota;
			this.v_Mes = v_Mes;
			this.v_Periodo = v_Periodo;
        }
    }
}
