//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:07:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class planillavaloresproyeccionquintaDto
    {
        [DataMember()]
        public String v_Periodo { get; set; }

        [DataMember()]
        public Nullable<Int32> i_IdMes { get; set; }

        [DataMember()]
        public Nullable<Int32> i_MesesProyectados { get; set; }

        [DataMember()]
        public Nullable<Int32> i_GratificacionesProyectadas { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Fraccionamiento { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Int32 i_Id { get; set; }

        public planillavaloresproyeccionquintaDto()
        {
        }

        public planillavaloresproyeccionquintaDto(String v_Periodo, Nullable<Int32> i_IdMes, Nullable<Int32> i_MesesProyectados, Nullable<Int32> i_GratificacionesProyectadas, Nullable<Int32> i_Fraccionamiento, Nullable<Int32> i_Eliminado, Int32 i_Id)
        {
			this.v_Periodo = v_Periodo;
			this.i_IdMes = i_IdMes;
			this.i_MesesProyectados = i_MesesProyectados;
			this.i_GratificacionesProyectadas = i_GratificacionesProyectadas;
			this.i_Fraccionamiento = i_Fraccionamiento;
			this.i_Eliminado = i_Eliminado;
			this.i_Id = i_Id;
        }
    }
}
