//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:11:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class pagopendienteDto
    {
        [DataMember()]
        public String v_IdPagoPendiente { get; set; }

        [DataMember()]
        public String v_IdCompra { get; set; }

        [DataMember()]
        public String v_IdLiqCompra { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_Acuenta { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_Saldo { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_InsertaFecha { get; set; }

        [DataMember()]
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_ActualizaFecha { get; set; }

        [DataMember()]
        public compraDto compra { get; set; }

        [DataMember()]
        public liquidacioncompraDto liquidacioncompra { get; set; }

        public pagopendienteDto()
        {
        }

        public pagopendienteDto(String v_IdPagoPendiente, String v_IdCompra, String v_IdLiqCompra, Nullable<Decimal> d_Acuenta, Nullable<Decimal> d_Saldo, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_ActualizaFecha, compraDto compra, liquidacioncompraDto liquidacioncompra)
        {
			this.v_IdPagoPendiente = v_IdPagoPendiente;
			this.v_IdCompra = v_IdCompra;
			this.v_IdLiqCompra = v_IdLiqCompra;
			this.d_Acuenta = d_Acuenta;
			this.d_Saldo = d_Saldo;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.compra = compra;
			this.liquidacioncompra = liquidacioncompra;
        }
    }
}
