//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:12:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="color"/> and <see cref="colorDto"/>.
    /// </summary>
    public static partial class colorAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="colorDto"/> converted from <see cref="color"/>.</param>
        static partial void OnDTO(this color entity, colorDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="color"/> converted from <see cref="colorDto"/>.</param>
        static partial void OnEntity(this colorDto dto, color entity);

        /// <summary>
        /// Converts this instance of <see cref="colorDto"/> to an instance of <see cref="color"/>.
        /// </summary>
        /// <param name="dto"><see cref="colorDto"/> to convert.</param>
        public static color ToEntity(this colorDto dto)
        {
            if (dto == null) return null;

            var entity = new color();

            entity.v_IdColor = dto.v_IdColor;
            entity.v_CodColor = dto.v_CodColor;
            entity.v_Nombre = dto.v_Nombre;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="color"/> to an instance of <see cref="colorDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="color"/> to convert.</param>
        public static colorDto ToDTO(this color entity)
        {
            if (entity == null) return null;

            var dto = new colorDto();

            dto.v_IdColor = entity.v_IdColor;
            dto.v_CodColor = entity.v_CodColor;
            dto.v_Nombre = entity.v_Nombre;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="colorDto"/> to an instance of <see cref="color"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<color> ToEntities(this IEnumerable<colorDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="color"/> to an instance of <see cref="colorDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<colorDto> ToDTOs(this IEnumerable<color> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
