//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:12:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="concepto"/> and <see cref="conceptoDto"/>.
    /// </summary>
    public static partial class conceptoAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="conceptoDto"/> converted from <see cref="concepto"/>.</param>
        static partial void OnDTO(this concepto entity, conceptoDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="concepto"/> converted from <see cref="conceptoDto"/>.</param>
        static partial void OnEntity(this conceptoDto dto, concepto entity);

        /// <summary>
        /// Converts this instance of <see cref="conceptoDto"/> to an instance of <see cref="concepto"/>.
        /// </summary>
        /// <param name="dto"><see cref="conceptoDto"/> to convert.</param>
        public static concepto ToEntity(this conceptoDto dto)
        {
            if (dto == null) return null;

            var entity = new concepto();

            entity.v_IdConcepto = dto.v_IdConcepto;
            entity.v_Codigo = dto.v_Codigo;
            entity.v_Nombre = dto.v_Nombre;
            entity.i_IdArea = dto.i_IdArea;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;
            entity.v_Periodo = dto.v_Periodo;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="concepto"/> to an instance of <see cref="conceptoDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="concepto"/> to convert.</param>
        public static conceptoDto ToDTO(this concepto entity)
        {
            if (entity == null) return null;

            var dto = new conceptoDto();

            dto.v_IdConcepto = entity.v_IdConcepto;
            dto.v_Codigo = entity.v_Codigo;
            dto.v_Nombre = entity.v_Nombre;
            dto.i_IdArea = entity.i_IdArea;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;
            dto.v_Periodo = entity.v_Periodo;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="conceptoDto"/> to an instance of <see cref="concepto"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<concepto> ToEntities(this IEnumerable<conceptoDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="concepto"/> to an instance of <see cref="conceptoDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<conceptoDto> ToDTOs(this IEnumerable<concepto> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
