//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:13:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="diariodetalle"/> and <see cref="diariodetalleDto"/>.
    /// </summary>
    public static partial class diariodetalleAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="diariodetalleDto"/> converted from <see cref="diariodetalle"/>.</param>
        static partial void OnDTO(this diariodetalle entity, diariodetalleDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="diariodetalle"/> converted from <see cref="diariodetalleDto"/>.</param>
        static partial void OnEntity(this diariodetalleDto dto, diariodetalle entity);

        /// <summary>
        /// Converts this instance of <see cref="diariodetalleDto"/> to an instance of <see cref="diariodetalle"/>.
        /// </summary>
        /// <param name="dto"><see cref="diariodetalleDto"/> to convert.</param>
        public static diariodetalle ToEntity(this diariodetalleDto dto)
        {
            if (dto == null) return null;

            var entity = new diariodetalle();

            entity.v_IdDiarioDetalle = dto.v_IdDiarioDetalle;
            entity.i_EsDestino = dto.i_EsDestino;
            entity.v_IdDiario = dto.v_IdDiario;
            entity.v_IdCliente = dto.v_IdCliente;
            entity.v_NroCuenta = dto.v_NroCuenta;
            entity.v_Naturaleza = dto.v_Naturaleza;
            entity.d_Importe = dto.d_Importe;
            entity.d_Cambio = dto.d_Cambio;
            entity.i_IdCentroCostos = dto.i_IdCentroCostos;
            entity.i_IdTipoDocumento = dto.i_IdTipoDocumento;
            entity.v_NroDocumento = dto.v_NroDocumento;
            entity.t_Fecha = dto.t_Fecha;
            entity.i_IdTipoDocumentoRef = dto.i_IdTipoDocumentoRef;
            entity.v_NroDocumentoRef = dto.v_NroDocumentoRef;
            entity.v_Analisis = dto.v_Analisis;
            entity.v_OrigenDestino = dto.v_OrigenDestino;
            entity.v_Pedido = dto.v_Pedido;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;
            entity.i_IdPatrimonioNeto = dto.i_IdPatrimonioNeto;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="diariodetalle"/> to an instance of <see cref="diariodetalleDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="diariodetalle"/> to convert.</param>
        public static diariodetalleDto ToDTO(this diariodetalle entity)
        {
            if (entity == null) return null;

            var dto = new diariodetalleDto();

            dto.v_IdDiarioDetalle = entity.v_IdDiarioDetalle;
            dto.i_EsDestino = entity.i_EsDestino;
            dto.v_IdDiario = entity.v_IdDiario;
            dto.v_IdCliente = entity.v_IdCliente;
            dto.v_NroCuenta = entity.v_NroCuenta;
            dto.v_Naturaleza = entity.v_Naturaleza;
            dto.d_Importe = entity.d_Importe;
            dto.d_Cambio = entity.d_Cambio;
            dto.i_IdCentroCostos = entity.i_IdCentroCostos;
            dto.i_IdTipoDocumento = entity.i_IdTipoDocumento;
            dto.v_NroDocumento = entity.v_NroDocumento;
            dto.t_Fecha = entity.t_Fecha;
            dto.i_IdTipoDocumentoRef = entity.i_IdTipoDocumentoRef;
            dto.v_NroDocumentoRef = entity.v_NroDocumentoRef;
            dto.v_Analisis = entity.v_Analisis;
            dto.v_OrigenDestino = entity.v_OrigenDestino;
            dto.v_Pedido = entity.v_Pedido;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;
            dto.i_IdPatrimonioNeto = entity.i_IdPatrimonioNeto;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="diariodetalleDto"/> to an instance of <see cref="diariodetalle"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<diariodetalle> ToEntities(this IEnumerable<diariodetalleDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="diariodetalle"/> to an instance of <see cref="diariodetalleDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<diariodetalleDto> ToDTOs(this IEnumerable<diariodetalle> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
