//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:13:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="letrasdetalle"/> and <see cref="letrasdetalleDto"/>.
    /// </summary>
    public static partial class letrasdetalleAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="letrasdetalleDto"/> converted from <see cref="letrasdetalle"/>.</param>
        static partial void OnDTO(this letrasdetalle entity, letrasdetalleDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="letrasdetalle"/> converted from <see cref="letrasdetalleDto"/>.</param>
        static partial void OnEntity(this letrasdetalleDto dto, letrasdetalle entity);

        /// <summary>
        /// Converts this instance of <see cref="letrasdetalleDto"/> to an instance of <see cref="letrasdetalle"/>.
        /// </summary>
        /// <param name="dto"><see cref="letrasdetalleDto"/> to convert.</param>
        public static letrasdetalle ToEntity(this letrasdetalleDto dto)
        {
            if (dto == null) return null;

            var entity = new letrasdetalle();

            entity.v_IdLetrasDetalle = dto.v_IdLetrasDetalle;
            entity.v_IdLetras = dto.v_IdLetras;
            entity.v_IdLetrasRenovacion = dto.v_IdLetrasRenovacion;
            entity.v_IdCliente = dto.v_IdCliente;
            entity.i_IdTipoDocumento = dto.i_IdTipoDocumento;
            entity.v_Serie = dto.v_Serie;
            entity.v_Correlativo = dto.v_Correlativo;
            entity.i_TotalDias = dto.i_TotalDias;
            entity.t_FechaEmision = dto.t_FechaEmision;
            entity.t_FechaVencimiento = dto.t_FechaVencimiento;
            entity.d_Importe = dto.d_Importe;
            entity.i_Pagada = dto.i_Pagada;
            entity.i_EsSaldoInicial = dto.i_EsSaldoInicial;
            entity.i_IdMoneda = dto.i_IdMoneda;
            entity.d_TipoCambio = dto.d_TipoCambio;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;
            entity.v_NroUnico = dto.v_NroUnico;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="letrasdetalle"/> to an instance of <see cref="letrasdetalleDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="letrasdetalle"/> to convert.</param>
        public static letrasdetalleDto ToDTO(this letrasdetalle entity)
        {
            if (entity == null) return null;

            var dto = new letrasdetalleDto();

            dto.v_IdLetrasDetalle = entity.v_IdLetrasDetalle;
            dto.v_IdLetras = entity.v_IdLetras;
            dto.v_IdLetrasRenovacion = entity.v_IdLetrasRenovacion;
            dto.v_IdCliente = entity.v_IdCliente;
            dto.i_IdTipoDocumento = entity.i_IdTipoDocumento;
            dto.v_Serie = entity.v_Serie;
            dto.v_Correlativo = entity.v_Correlativo;
            dto.i_TotalDias = entity.i_TotalDias;
            dto.t_FechaEmision = entity.t_FechaEmision;
            dto.t_FechaVencimiento = entity.t_FechaVencimiento;
            dto.d_Importe = entity.d_Importe;
            dto.i_Pagada = entity.i_Pagada;
            dto.i_EsSaldoInicial = entity.i_EsSaldoInicial;
            dto.i_IdMoneda = entity.i_IdMoneda;
            dto.d_TipoCambio = entity.d_TipoCambio;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;
            dto.v_NroUnico = entity.v_NroUnico;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="letrasdetalleDto"/> to an instance of <see cref="letrasdetalle"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<letrasdetalle> ToEntities(this IEnumerable<letrasdetalleDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="letrasdetalle"/> to an instance of <see cref="letrasdetalleDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<letrasdetalleDto> ToDTOs(this IEnumerable<letrasdetalle> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
