//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:14:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="planillavariablestrabajador"/> and <see cref="planillavariablestrabajadorDto"/>.
    /// </summary>
    public static partial class planillavariablestrabajadorAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="planillavariablestrabajadorDto"/> converted from <see cref="planillavariablestrabajador"/>.</param>
        static partial void OnDTO(this planillavariablestrabajador entity, planillavariablestrabajadorDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="planillavariablestrabajador"/> converted from <see cref="planillavariablestrabajadorDto"/>.</param>
        static partial void OnEntity(this planillavariablestrabajadorDto dto, planillavariablestrabajador entity);

        /// <summary>
        /// Converts this instance of <see cref="planillavariablestrabajadorDto"/> to an instance of <see cref="planillavariablestrabajador"/>.
        /// </summary>
        /// <param name="dto"><see cref="planillavariablestrabajadorDto"/> to convert.</param>
        public static planillavariablestrabajador ToEntity(this planillavariablestrabajadorDto dto)
        {
            if (dto == null) return null;

            var entity = new planillavariablestrabajador();

            entity.v_IdPlanillaVariablesTrabajador = dto.v_IdPlanillaVariablesTrabajador;
            entity.i_IdPlanillaNumeracion = dto.i_IdPlanillaNumeracion;
            entity.v_IdTrabajador = dto.v_IdTrabajador;
            entity.v_IdContrato = dto.v_IdContrato;
            entity.i_Movilidad = dto.i_Movilidad;
            entity.d_Imp = dto.d_Imp;
            entity.i_DiasLaborados = dto.i_DiasLaborados;
            entity.i_DiasNoLaborados = dto.i_DiasNoLaborados;
            entity.i_DiasSubsidiados = dto.i_DiasSubsidiados;
            entity.i_DiasLaboradosBP = dto.i_DiasLaboradosBP;
            entity.d_HorasLaboradosBP = dto.d_HorasLaboradosBP;
            entity.d_TiempoTardanza = dto.d_TiempoTardanza;
            entity.i_Pago = dto.i_Pago;
            entity.i_AfectoSenati = dto.i_AfectoSenati;
            entity.i_NoAplicarDCTOLeyesAFP = dto.i_NoAplicarDCTOLeyesAFP;
            entity.i_AfectoSCTR = dto.i_AfectoSCTR;
            entity.i_AfectoSCTRPen = dto.i_AfectoSCTRPen;
            entity.t_FechaVacacionesInicio = dto.t_FechaVacacionesInicio;
            entity.t_FechaVacacionesFin = dto.t_FechaVacacionesFin;
            entity.d_TotalIngresoSoles = dto.d_TotalIngresoSoles;
            entity.d_TotalIngresoDolares = dto.d_TotalIngresoDolares;
            entity.d_TotalDescuentoSoles = dto.d_TotalDescuentoSoles;
            entity.d_TotalDescuentoDolares = dto.d_TotalDescuentoDolares;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;
            entity.i_TieneVacaciones = dto.i_TieneVacaciones;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="planillavariablestrabajador"/> to an instance of <see cref="planillavariablestrabajadorDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="planillavariablestrabajador"/> to convert.</param>
        public static planillavariablestrabajadorDto ToDTO(this planillavariablestrabajador entity)
        {
            if (entity == null) return null;

            var dto = new planillavariablestrabajadorDto();

            dto.v_IdPlanillaVariablesTrabajador = entity.v_IdPlanillaVariablesTrabajador;
            dto.i_IdPlanillaNumeracion = entity.i_IdPlanillaNumeracion;
            dto.v_IdTrabajador = entity.v_IdTrabajador;
            dto.v_IdContrato = entity.v_IdContrato;
            dto.i_Movilidad = entity.i_Movilidad;
            dto.d_Imp = entity.d_Imp;
            dto.i_DiasLaborados = entity.i_DiasLaborados;
            dto.i_DiasNoLaborados = entity.i_DiasNoLaborados;
            dto.i_DiasSubsidiados = entity.i_DiasSubsidiados;
            dto.i_DiasLaboradosBP = entity.i_DiasLaboradosBP;
            dto.d_HorasLaboradosBP = entity.d_HorasLaboradosBP;
            dto.d_TiempoTardanza = entity.d_TiempoTardanza;
            dto.i_Pago = entity.i_Pago;
            dto.i_AfectoSenati = entity.i_AfectoSenati;
            dto.i_NoAplicarDCTOLeyesAFP = entity.i_NoAplicarDCTOLeyesAFP;
            dto.i_AfectoSCTR = entity.i_AfectoSCTR;
            dto.i_AfectoSCTRPen = entity.i_AfectoSCTRPen;
            dto.t_FechaVacacionesInicio = entity.t_FechaVacacionesInicio;
            dto.t_FechaVacacionesFin = entity.t_FechaVacacionesFin;
            dto.d_TotalIngresoSoles = entity.d_TotalIngresoSoles;
            dto.d_TotalIngresoDolares = entity.d_TotalIngresoDolares;
            dto.d_TotalDescuentoSoles = entity.d_TotalDescuentoSoles;
            dto.d_TotalDescuentoDolares = entity.d_TotalDescuentoDolares;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;
            dto.i_TieneVacaciones = entity.i_TieneVacaciones;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="planillavariablestrabajadorDto"/> to an instance of <see cref="planillavariablestrabajador"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<planillavariablestrabajador> ToEntities(this IEnumerable<planillavariablestrabajadorDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="planillavariablestrabajador"/> to an instance of <see cref="planillavariablestrabajadorDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<planillavariablestrabajadorDto> ToDTOs(this IEnumerable<planillavariablestrabajador> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
