//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:14:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="recibohonorariodetalle"/> and <see cref="recibohonorariodetalleDto"/>.
    /// </summary>
    public static partial class recibohonorariodetalleAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="recibohonorariodetalleDto"/> converted from <see cref="recibohonorariodetalle"/>.</param>
        static partial void OnDTO(this recibohonorariodetalle entity, recibohonorariodetalleDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="recibohonorariodetalle"/> converted from <see cref="recibohonorariodetalleDto"/>.</param>
        static partial void OnEntity(this recibohonorariodetalleDto dto, recibohonorariodetalle entity);

        /// <summary>
        /// Converts this instance of <see cref="recibohonorariodetalleDto"/> to an instance of <see cref="recibohonorariodetalle"/>.
        /// </summary>
        /// <param name="dto"><see cref="recibohonorariodetalleDto"/> to convert.</param>
        public static recibohonorariodetalle ToEntity(this recibohonorariodetalleDto dto)
        {
            if (dto == null) return null;

            var entity = new recibohonorariodetalle();

            entity.v_IdReciboHonorarioDetalle = dto.v_IdReciboHonorarioDetalle;
            entity.v_IdReciboHonorario = dto.v_IdReciboHonorario;
            entity.v_NroCuenta = dto.v_NroCuenta;
            entity.i_CCosto = dto.i_CCosto;
            entity.d_ImporteSoles = dto.d_ImporteSoles;
            entity.d_ImporteDolares = dto.d_ImporteDolares;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="recibohonorariodetalle"/> to an instance of <see cref="recibohonorariodetalleDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="recibohonorariodetalle"/> to convert.</param>
        public static recibohonorariodetalleDto ToDTO(this recibohonorariodetalle entity)
        {
            if (entity == null) return null;

            var dto = new recibohonorariodetalleDto();

            dto.v_IdReciboHonorarioDetalle = entity.v_IdReciboHonorarioDetalle;
            dto.v_IdReciboHonorario = entity.v_IdReciboHonorario;
            dto.v_NroCuenta = entity.v_NroCuenta;
            dto.i_CCosto = entity.i_CCosto;
            dto.d_ImporteSoles = entity.d_ImporteSoles;
            dto.d_ImporteDolares = entity.d_ImporteDolares;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="recibohonorariodetalleDto"/> to an instance of <see cref="recibohonorariodetalle"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<recibohonorariodetalle> ToEntities(this IEnumerable<recibohonorariodetalleDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="recibohonorariodetalle"/> to an instance of <see cref="recibohonorariodetalleDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<recibohonorariodetalleDto> ToDTOs(this IEnumerable<recibohonorariodetalle> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
