//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/09/13 - 15:35:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class nbs_ordentrabajoDto
    {
        [DataMember()]
        public String v_IdOrdenTrabajo { get; set; }

        [DataMember()]
        public String v_Periodo { get; set; }

        [DataMember()]
        public String v_Mes { get; set; }

        [DataMember()]
        public String v_Correlativo { get; set; }

        [DataMember()]
        public String v_NroOrdenTrabajo { get; set; }

        [DataMember()]
        public String v_IdCliente { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_FechaRegistro { get; set; }

        [DataMember()]
        public String v_Referencia { get; set; }

        [DataMember()]
        public String v_Glosa { get; set; }

        [DataMember()]
        public String v_NroOrdenCompra { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_Total { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_InsertaFecha { get; set; }

        [DataMember()]
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_ActualizaFecha { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_TotalRegistral { get; set; }

        [DataMember()]
        public Nullable<Int32> i_IdEstado { get; set; }

        [DataMember()]
        public String v_IdResponsable { get; set; }

        public nbs_ordentrabajoDto()
        {
        }

        public nbs_ordentrabajoDto(String v_IdOrdenTrabajo, String v_Periodo, String v_Mes, String v_Correlativo, String v_NroOrdenTrabajo, String v_IdCliente, Nullable<DateTime> t_FechaRegistro, String v_Referencia, String v_Glosa, String v_NroOrdenCompra, Nullable<Decimal> d_Total, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_ActualizaFecha, Nullable<Decimal> d_TotalRegistral, Nullable<Int32> i_IdEstado, String v_IdResponsable)
        {
			this.v_IdOrdenTrabajo = v_IdOrdenTrabajo;
			this.v_Periodo = v_Periodo;
			this.v_Mes = v_Mes;
			this.v_Correlativo = v_Correlativo;
			this.v_NroOrdenTrabajo = v_NroOrdenTrabajo;
			this.v_IdCliente = v_IdCliente;
			this.t_FechaRegistro = t_FechaRegistro;
			this.v_Referencia = v_Referencia;
			this.v_Glosa = v_Glosa;
			this.v_NroOrdenCompra = v_NroOrdenCompra;
			this.d_Total = d_Total;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.d_TotalRegistral = d_TotalRegistral;
			this.i_IdEstado = i_IdEstado;
			this.v_IdResponsable = v_IdResponsable;
        }
    }
}
