//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:12:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class productorecetasalidaDto
    {
        [DataMember()]
        public Int32 i_IdRecetaSalida { get; set; }

        [DataMember()]
        public String v_IdProductoTributo { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Eliminado { get; set; }

        [DataMember()]
        public Nullable<Int32> i_InsertaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_InsertaFecha { get; set; }

        [DataMember()]
        public Nullable<Int32> i_ActualizaIdUsuario { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_ActualizaFecha { get; set; }

        [DataMember()]
        public String v_IdProductoExportacion { get; set; }

        [DataMember()]
        public productodetalleDto productodetalle { get; set; }

        public productorecetasalidaDto()
        {
        }

        public productorecetasalidaDto(Int32 i_IdRecetaSalida, String v_IdProductoTributo, Nullable<Int32> i_Eliminado, Nullable<Int32> i_InsertaIdUsuario, Nullable<DateTime> t_InsertaFecha, Nullable<Int32> i_ActualizaIdUsuario, Nullable<DateTime> t_ActualizaFecha, String v_IdProductoExportacion, productodetalleDto productodetalle)
        {
			this.i_IdRecetaSalida = i_IdRecetaSalida;
			this.v_IdProductoTributo = v_IdProductoTributo;
			this.i_Eliminado = i_Eliminado;
			this.i_InsertaIdUsuario = i_InsertaIdUsuario;
			this.t_InsertaFecha = t_InsertaFecha;
			this.i_ActualizaIdUsuario = i_ActualizaIdUsuario;
			this.t_ActualizaFecha = t_ActualizaFecha;
			this.v_IdProductoExportacion = v_IdProductoExportacion;
			this.productodetalle = productodetalle;
        }
    }
}
