//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/10/02 - 09:33:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="ordenproduccion"/> and <see cref="ordenproduccionDto"/>.
    /// </summary>
    public static partial class ordenproduccionAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="ordenproduccionDto"/> converted from <see cref="ordenproduccion"/>.</param>
        static partial void OnDTO(this ordenproduccion entity, ordenproduccionDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="ordenproduccion"/> converted from <see cref="ordenproduccionDto"/>.</param>
        static partial void OnEntity(this ordenproduccionDto dto, ordenproduccion entity);

        /// <summary>
        /// Converts this instance of <see cref="ordenproduccionDto"/> to an instance of <see cref="ordenproduccion"/>.
        /// </summary>
        /// <param name="dto"><see cref="ordenproduccionDto"/> to convert.</param>
        public static ordenproduccion ToEntity(this ordenproduccionDto dto)
        {
            if (dto == null) return null;

            var entity = new ordenproduccion();

            entity.i_IdOrdenProduccion = dto.i_IdOrdenProduccion;
            entity.v_IdProductoDetalle = dto.v_IdProductoDetalle;
            entity.v_Mes = dto.v_Mes;
            entity.v_Correlativo = dto.v_Correlativo;
            entity.v_Periodo = dto.v_Periodo;
            entity.t_FechaRegistro = dto.t_FechaRegistro;
            entity.v_Observacion = dto.v_Observacion;
            entity.t_FechaInicio = dto.t_FechaInicio;
            entity.t_FechaTermino = dto.t_FechaTermino;
            entity.d_Cantidad = dto.d_Cantidad;
            entity.d_CantidadUnidadMedida = dto.d_CantidadUnidadMedida;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="ordenproduccion"/> to an instance of <see cref="ordenproduccionDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="ordenproduccion"/> to convert.</param>
        public static ordenproduccionDto ToDTO(this ordenproduccion entity)
        {
            if (entity == null) return null;

            var dto = new ordenproduccionDto();

            dto.i_IdOrdenProduccion = entity.i_IdOrdenProduccion;
            dto.v_IdProductoDetalle = entity.v_IdProductoDetalle;
            dto.v_Mes = entity.v_Mes;
            dto.v_Correlativo = entity.v_Correlativo;
            dto.v_Periodo = entity.v_Periodo;
            dto.t_FechaRegistro = entity.t_FechaRegistro;
            dto.v_Observacion = entity.v_Observacion;
            dto.t_FechaInicio = entity.t_FechaInicio;
            dto.t_FechaTermino = entity.t_FechaTermino;
            dto.d_Cantidad = entity.d_Cantidad;
            dto.d_CantidadUnidadMedida = entity.d_CantidadUnidadMedida;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="ordenproduccionDto"/> to an instance of <see cref="ordenproduccion"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<ordenproduccion> ToEntities(this IEnumerable<ordenproduccionDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="ordenproduccion"/> to an instance of <see cref="ordenproduccionDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<ordenproduccionDto> ToDTOs(this IEnumerable<ordenproduccion> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
