//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:07:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class loghistorialDto
    {
        [DataMember()]
        public Int32 i_IdHistorial { get; set; }

        [DataMember()]
        public String v_Accion { get; set; }

        [DataMember()]
        public String v_NombrePC { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_FechaHora { get; set; }

        public loghistorialDto()
        {
        }

        public loghistorialDto(Int32 i_IdHistorial, String v_Accion, String v_NombrePC, Nullable<DateTime> t_FechaHora)
        {
			this.i_IdHistorial = i_IdHistorial;
			this.v_Accion = v_Accion;
			this.v_NombrePC = v_NombrePC;
			this.t_FechaHora = t_FechaHora;
        }
    }
}
