//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/10/02 - 09:33:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="movimientodetalle"/> and <see cref="movimientodetalleDto"/>.
    /// </summary>
    public static partial class movimientodetalleAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="movimientodetalleDto"/> converted from <see cref="movimientodetalle"/>.</param>
        static partial void OnDTO(this movimientodetalle entity, movimientodetalleDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="movimientodetalle"/> converted from <see cref="movimientodetalleDto"/>.</param>
        static partial void OnEntity(this movimientodetalleDto dto, movimientodetalle entity);

        /// <summary>
        /// Converts this instance of <see cref="movimientodetalleDto"/> to an instance of <see cref="movimientodetalle"/>.
        /// </summary>
        /// <param name="dto"><see cref="movimientodetalleDto"/> to convert.</param>
        public static movimientodetalle ToEntity(this movimientodetalleDto dto)
        {
            if (dto == null) return null;

            var entity = new movimientodetalle();

            entity.v_IdMovimientoDetalle = dto.v_IdMovimientoDetalle;
            entity.v_IdMovimiento = dto.v_IdMovimiento;
            entity.v_IdProductoDetalle = dto.v_IdProductoDetalle;
            entity.v_IdMovimientoDetalleTransferencia = dto.v_IdMovimientoDetalleTransferencia;
            entity.v_NroGuiaRemision = dto.v_NroGuiaRemision;
            entity.i_IdTipoDocumento = dto.i_IdTipoDocumento;
            entity.v_NumeroDocumento = dto.v_NumeroDocumento;
            entity.d_Cantidad = dto.d_Cantidad;
            entity.d_CantidadEmpaque = dto.d_CantidadEmpaque;
            entity.i_IdUnidad = dto.i_IdUnidad;
            entity.d_Precio = dto.d_Precio;
            entity.d_Total = dto.d_Total;
            entity.v_NroPedido = dto.v_NroPedido;
            entity.d_CantidadAdministrativa = dto.d_CantidadAdministrativa;
            entity.d_CantidadEmpaqueAdministrativa = dto.d_CantidadEmpaqueAdministrativa;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;
            entity.v_IdRecetaFinal = dto.v_IdRecetaFinal;
            entity.i_EsProductoFinal = dto.i_EsProductoFinal;
            entity.d_PrecioCambio = dto.d_PrecioCambio;
            entity.d_TotalCambio = dto.d_TotalCambio;
            entity.i_IdCentroCosto = dto.i_IdCentroCosto;
            entity.t_FechaCaducidad = dto.t_FechaCaducidad;
            entity.t_FechaFabricacion = dto.t_FechaFabricacion;
            entity.v_NroSerie = dto.v_NroSerie;
            entity.v_NroLote = dto.v_NroLote;
            entity.v_NroOrdenProduccion = dto.v_NroOrdenProduccion;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="movimientodetalle"/> to an instance of <see cref="movimientodetalleDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="movimientodetalle"/> to convert.</param>
        public static movimientodetalleDto ToDTO(this movimientodetalle entity)
        {
            if (entity == null) return null;

            var dto = new movimientodetalleDto();

            dto.v_IdMovimientoDetalle = entity.v_IdMovimientoDetalle;
            dto.v_IdMovimiento = entity.v_IdMovimiento;
            dto.v_IdProductoDetalle = entity.v_IdProductoDetalle;
            dto.v_IdMovimientoDetalleTransferencia = entity.v_IdMovimientoDetalleTransferencia;
            dto.v_NroGuiaRemision = entity.v_NroGuiaRemision;
            dto.i_IdTipoDocumento = entity.i_IdTipoDocumento;
            dto.v_NumeroDocumento = entity.v_NumeroDocumento;
            dto.d_Cantidad = entity.d_Cantidad;
            dto.d_CantidadEmpaque = entity.d_CantidadEmpaque;
            dto.i_IdUnidad = entity.i_IdUnidad;
            dto.d_Precio = entity.d_Precio;
            dto.d_Total = entity.d_Total;
            dto.v_NroPedido = entity.v_NroPedido;
            dto.d_CantidadAdministrativa = entity.d_CantidadAdministrativa;
            dto.d_CantidadEmpaqueAdministrativa = entity.d_CantidadEmpaqueAdministrativa;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;
            dto.v_IdRecetaFinal = entity.v_IdRecetaFinal;
            dto.i_EsProductoFinal = entity.i_EsProductoFinal;
            dto.d_PrecioCambio = entity.d_PrecioCambio;
            dto.d_TotalCambio = entity.d_TotalCambio;
            dto.i_IdCentroCosto = entity.i_IdCentroCosto;
            dto.t_FechaCaducidad = entity.t_FechaCaducidad;
            dto.t_FechaFabricacion = entity.t_FechaFabricacion;
            dto.v_NroSerie = entity.v_NroSerie;
            dto.v_NroLote = entity.v_NroLote;
            dto.v_NroOrdenProduccion = entity.v_NroOrdenProduccion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="movimientodetalleDto"/> to an instance of <see cref="movimientodetalle"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<movimientodetalle> ToEntities(this IEnumerable<movimientodetalleDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="movimientodetalle"/> to an instance of <see cref="movimientodetalleDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<movimientodetalleDto> ToDTOs(this IEnumerable<movimientodetalle> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
