//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/09/13 - 15:27:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace SAMBHS.Common.BE
{
    [DataContract()]
    public partial class planillaturnosdetalleDto
    {
        [DataMember()]
        public Int32 i_IdTurnoDetalle { get; set; }

        [DataMember()]
        public Nullable<Int32> i_IdTurno { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_IngresoI { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_SalidaI { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_IngresoII { get; set; }

        [DataMember()]
        public Nullable<DateTime> t_SalidaII { get; set; }

        [DataMember()]
        public Nullable<Decimal> d_HorasSemanales { get; set; }

        [DataMember()]
        public Nullable<Int32> i_IdDia { get; set; }

        [DataMember()]
        public Nullable<Int32> i_Asiste { get; set; }

        public planillaturnosdetalleDto()
        {
        }

        public planillaturnosdetalleDto(Int32 i_IdTurnoDetalle, Nullable<Int32> i_IdTurno, Nullable<DateTime> t_IngresoI, Nullable<DateTime> t_SalidaI, Nullable<DateTime> t_IngresoII, Nullable<DateTime> t_SalidaII, Nullable<Decimal> d_HorasSemanales, Nullable<Int32> i_IdDia, Nullable<Int32> i_Asiste)
        {
			this.i_IdTurnoDetalle = i_IdTurnoDetalle;
			this.i_IdTurno = i_IdTurno;
			this.t_IngresoI = t_IngresoI;
			this.t_SalidaI = t_SalidaI;
			this.t_IngresoII = t_IngresoII;
			this.t_SalidaII = t_SalidaII;
			this.d_HorasSemanales = d_HorasSemanales;
			this.i_IdDia = i_IdDia;
			this.i_Asiste = i_Asiste;
        }
    }
}
