//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/11/24 - 15:06:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="warehouse"/> and <see cref="warehouseDto"/>.
    /// </summary>
    public static partial class warehouseAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="warehouseDto"/> converted from <see cref="warehouse"/>.</param>
        static partial void OnDTO(this warehouse entity, warehouseDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="warehouse"/> converted from <see cref="warehouseDto"/>.</param>
        static partial void OnEntity(this warehouseDto dto, warehouse entity);

        /// <summary>
        /// Converts this instance of <see cref="warehouseDto"/> to an instance of <see cref="warehouse"/>.
        /// </summary>
        /// <param name="dto"><see cref="warehouseDto"/> to convert.</param>
        public static warehouse ToEntity(this warehouseDto dto)
        {
            if (dto == null) return null;

            var entity = new warehouse();

            entity.i_WarehouseId = dto.i_WarehouseId;
            entity.v_Name = dto.v_Name;
            entity.v_Address = dto.v_Address;
            entity.v_PhoneNumber = dto.v_PhoneNumber;
            entity.v_CommercialName = dto.v_CommercialName;
            entity.v_TicketSerialNumber = dto.v_TicketSerialNumber;
            entity.v_EstablishmentCode = dto.v_EstablishmentCode;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.i_InsertUserId = dto.i_InsertUserId;
            entity.d_InsertDate = dto.d_InsertDate;
            entity.i_UpdateUserId = dto.i_UpdateUserId;
            entity.d_UpdateDate = dto.d_UpdateDate;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="warehouse"/> to an instance of <see cref="warehouseDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="warehouse"/> to convert.</param>
        public static warehouseDto ToDTO(this warehouse entity)
        {
            if (entity == null) return null;

            var dto = new warehouseDto();

            dto.i_WarehouseId = entity.i_WarehouseId;
            dto.v_Name = entity.v_Name;
            dto.v_Address = entity.v_Address;
            dto.v_PhoneNumber = entity.v_PhoneNumber;
            dto.v_CommercialName = entity.v_CommercialName;
            dto.v_TicketSerialNumber = entity.v_TicketSerialNumber;
            dto.v_EstablishmentCode = entity.v_EstablishmentCode;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.i_InsertUserId = entity.i_InsertUserId;
            dto.d_InsertDate = entity.d_InsertDate;
            dto.i_UpdateUserId = entity.i_UpdateUserId;
            dto.d_UpdateDate = entity.d_UpdateDate;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="warehouseDto"/> to an instance of <see cref="warehouse"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<warehouse> ToEntities(this IEnumerable<warehouseDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="warehouse"/> to an instance of <see cref="warehouseDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<warehouseDto> ToDTOs(this IEnumerable<warehouse> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
