//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:12:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="cierremensual"/> and <see cref="cierremensualDto"/>.
    /// </summary>
    public static partial class cierremensualAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="cierremensualDto"/> converted from <see cref="cierremensual"/>.</param>
        static partial void OnDTO(this cierremensual entity, cierremensualDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="cierremensual"/> converted from <see cref="cierremensualDto"/>.</param>
        static partial void OnEntity(this cierremensualDto dto, cierremensual entity);

        /// <summary>
        /// Converts this instance of <see cref="cierremensualDto"/> to an instance of <see cref="cierremensual"/>.
        /// </summary>
        /// <param name="dto"><see cref="cierremensualDto"/> to convert.</param>
        public static cierremensual ToEntity(this cierremensualDto dto)
        {
            if (dto == null) return null;

            var entity = new cierremensual();

            entity.v_IdCierreMensaual = dto.v_IdCierreMensaual;
            entity.v_Mes = dto.v_Mes;
            entity.v_Periodo = dto.v_Periodo;
            entity.i_IdProceso = dto.i_IdProceso;
            entity.i_Cerrado = dto.i_Cerrado;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="cierremensual"/> to an instance of <see cref="cierremensualDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="cierremensual"/> to convert.</param>
        public static cierremensualDto ToDTO(this cierremensual entity)
        {
            if (entity == null) return null;

            var dto = new cierremensualDto();

            dto.v_IdCierreMensaual = entity.v_IdCierreMensaual;
            dto.v_Mes = entity.v_Mes;
            dto.v_Periodo = entity.v_Periodo;
            dto.i_IdProceso = entity.i_IdProceso;
            dto.i_Cerrado = entity.i_Cerrado;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="cierremensualDto"/> to an instance of <see cref="cierremensual"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<cierremensual> ToEntities(this IEnumerable<cierremensualDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="cierremensual"/> to an instance of <see cref="cierremensualDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<cierremensualDto> ToDTOs(this IEnumerable<cierremensual> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
