//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/07/13 - 15:13:38
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using SAMBHS.Common.DataModel;

namespace SAMBHS.Common.BE
{

    /// <summary>
    /// Assembler for <see cref="letrascanje"/> and <see cref="letrascanjeDto"/>.
    /// </summary>
    public static partial class letrascanjeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="letrascanjeDto"/> converted from <see cref="letrascanje"/>.</param>
        static partial void OnDTO(this letrascanje entity, letrascanjeDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="letrascanje"/> converted from <see cref="letrascanjeDto"/>.</param>
        static partial void OnEntity(this letrascanjeDto dto, letrascanje entity);

        /// <summary>
        /// Converts this instance of <see cref="letrascanjeDto"/> to an instance of <see cref="letrascanje"/>.
        /// </summary>
        /// <param name="dto"><see cref="letrascanjeDto"/> to convert.</param>
        public static letrascanje ToEntity(this letrascanjeDto dto)
        {
            if (dto == null) return null;

            var entity = new letrascanje();

            entity.v_IdLetrasCanje = dto.v_IdLetrasCanje;
            entity.v_IdLetras = dto.v_IdLetras;
            entity.v_IdVenta = dto.v_IdVenta;
            entity.v_IdLetrasDetalle = dto.v_IdLetrasDetalle;
            entity.d_MontoCanjeado = dto.d_MontoCanjeado;
            entity.i_Eliminado = dto.i_Eliminado;
            entity.i_InsertaIdUsuario = dto.i_InsertaIdUsuario;
            entity.t_InsertaFecha = dto.t_InsertaFecha;
            entity.i_ActualizaIdUsuario = dto.i_ActualizaIdUsuario;
            entity.t_ActualizaFecha = dto.t_ActualizaFecha;
            entity.i_EsAdelanto = dto.i_EsAdelanto;
            entity.v_IdAdelanto = dto.v_IdAdelanto;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="letrascanje"/> to an instance of <see cref="letrascanjeDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="letrascanje"/> to convert.</param>
        public static letrascanjeDto ToDTO(this letrascanje entity)
        {
            if (entity == null) return null;

            var dto = new letrascanjeDto();

            dto.v_IdLetrasCanje = entity.v_IdLetrasCanje;
            dto.v_IdLetras = entity.v_IdLetras;
            dto.v_IdVenta = entity.v_IdVenta;
            dto.v_IdLetrasDetalle = entity.v_IdLetrasDetalle;
            dto.d_MontoCanjeado = entity.d_MontoCanjeado;
            dto.i_Eliminado = entity.i_Eliminado;
            dto.i_InsertaIdUsuario = entity.i_InsertaIdUsuario;
            dto.t_InsertaFecha = entity.t_InsertaFecha;
            dto.i_ActualizaIdUsuario = entity.i_ActualizaIdUsuario;
            dto.t_ActualizaFecha = entity.t_ActualizaFecha;
            dto.i_EsAdelanto = entity.i_EsAdelanto;
            dto.v_IdAdelanto = entity.v_IdAdelanto;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="letrascanjeDto"/> to an instance of <see cref="letrascanje"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<letrascanje> ToEntities(this IEnumerable<letrascanjeDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="letrascanje"/> to an instance of <see cref="letrascanjeDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<letrascanjeDto> ToDTOs(this IEnumerable<letrascanje> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
